security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    providers:
        # in_memory: { memory:  }
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$12$Z.krXZkqTxIUKfhRNc097urLjmDOeytPo/ip6FEzCke2JfWLkNVr2
                        roles: 'ROLE_ADMIN'
                    hanliang:
                        password: $2y$12$9lnJ9I0epFfBt1/pBH8FFOi8.y/7UBF/HDgCc6JUm.Zzq.fSuO0dG
                        roles: 'ROLE_USER'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~

            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }